name: Simple-express-run

on:
  schedule:
    - cron: '1 * * * *'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Current Time
        run: echo "The current time is $(date)"
  
  hello-2:
    runs-on: ubuntu-latest
    needs: hello  
    steps:
      - name: Step 1 of hello-2 job
        run: echo "Running step 1 of hello-2"
      
      - name: Step 2 of hello-2 job
        run: echo "Running step 2 of hello-2"

  hello-3:
    runs-on: ubuntu-latest
    needs: hello  
    steps:
      - name: Step 1 of hello-3 job
        run: echo "Running step 1 of hello-3"
      
      - name: Step 2 of hello-3 job
        run: echo "Running step 2 of hello-3"
    


  
